// Code generated by go generate
// This file was generated by robots at 2021-05-04 14:21:55.077372 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Optional is an optional T.
type Optional[T any] struct {
	value *T
}

// NewOptional creates an optional.Optional from a T.
func NewOptional[T any](v T) Optional[T] {
	return Optional[T]{&v}
}

// Set sets the T value.
func (i *Optional[T]) Set(v T) {
	i.value = &v
}

// Get returns the T value or an error if not present.
func (i Optional[T]) Get() (T, error) {
	if !i.Present() {
		var zero T
		return zero, errors.New("value not present")
	}
	return *i.value, nil
}

// MustGet returns the T value or panics if not present.
func (i Optional[T]) MustGet() T {
	if !i.Present() {
		panic("value not present")
	}
	return *i.value
}

// Present returns whether or not the value is present.
func (i Optional[T]) Present() bool {
	return i.value != nil
}

// OrElse returns the T value or a default value if the value is not present.
func (i Optional[T]) OrElse(v T) T {
	if i.Present() {
		return *i.value
	}
	return v
}

// If calls the function f with the value if the value is present.
func (i Optional[T]) If(fn func(T)) {
	if i.Present() {
		fn(*i.value)
	}
}

func (i Optional[T]) MarshalJSON() ([]byte, error) {
	if i.Present() {
		return json.Marshal(i.value)
	}
	return json.Marshal(nil)
}

func (i *Optional[T]) UnmarshalJSON(data []byte) error {

	if string(data) == "null" {
		i.value = nil
		return nil
	}

	var value T

	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	i.value = &value
	return nil
}
